# xpython-quarto
Debug repo for xeus-python RuntimeError

clone repo
```bash
# clone repo
git clone https://github.com/laguill/xpython-quarto.git
cd xpython-quarto

# init uv project
uv sync

# Try to preview file
uv run quarto preview test.qmd
```
